language: node_js
node_js:
- node
before_script:
- npm install -g bower
- npm install -g polymer-cli
- bower i
script: polymer build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/es6-bundled
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  slack:
    secure: UbT4OnnkDFBHF2K1UuzJRYU4lP5NAy7gAlFgrrmKlYhS1kf+0ZlQ0e6wpgZSvRRSopJ+rjNo9umFmh+B5/8/DIpoiv0U7WuErrFz7JY0szjG8xbPoobM/c9X44TS7NPo5r9XMVobyTjyXtrFGlmvOinVa7JTYslr7x0FG9pHV3iscobgBtc/rJpJ7cnw6BwSzP+aoRJ/h1ZuJgGWbWBUqYwjDfedI0TcTnDd64I11o1k74B6bzt46QF5J7L3/qQTkrlZvC8m4Bv4Z+GvpUiNyEVEtzjv2mJuhLyDDdtZaKJdgUTDfGaQNDm0yu71TSsDNF6eS6/25jJN0yaxWI4kYRtZ4i5DqHVPuGjH0sElRW+BbRtCjLvPvbkQLKha+a84DPet2eLdyVcW+D+UbpyfQzJzjFPYWwtuWf5BffR1MUXSU2XJTPkSvtw6QAyH3LHQBVCosmcQ6WZbr6WFhk524C3ebTJ59R2RsCWan8xt/gSZ3h9bolhiLC3wQh68mYR9XRxIy0cArHsPsrFKfZn84vAGZntuwmvOkiLayCU6+1HKcqYTABPY2CfEEruuY9y8qZy7nHNbmfLLJVBIPbUHvAW79HlaVNYmP2BPw3fOZ9nP2bhm6gqU2sjs4L3l0Jbjf40gvduybIBTHGGcXxIb9XF5VjA5Ez3gaDXnVrw6oCI=
